
package org.mines.douai.j2ee.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "YellowJacket", targetNamespace = "http://soap.j2ee.douai.mines.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface YellowJacket {


    /**
     * 
     * @param text
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPeopleCount", targetNamespace = "http://soap.j2ee.douai.mines.org/", className = "org.mines.douai.j2ee.soap.GetPeopleCount")
    @ResponseWrapper(localName = "getPeopleCountResponse", targetNamespace = "http://soap.j2ee.douai.mines.org/", className = "org.mines.douai.j2ee.soap.GetPeopleCountResponse")
    @Action(input = "http://soap.j2ee.douai.mines.org/YellowJacket/getPeopleCountRequest", output = "http://soap.j2ee.douai.mines.org/YellowJacket/getPeopleCountResponse")
    public int getPeopleCount(
        @WebParam(name = "text", targetNamespace = "")
        String text);

}
