
package org.mines.douai.j2ee.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "YellowJacketWebService", targetNamespace = "http://soap.j2ee.douai.mines.org/", wsdlLocation = "file:/D:/Mes%20Documents/Travail/ISIC/3A/TP_J2EE/TP_SOAP_SERVLET/src/YellowJacket.wsdl")
public class YellowJacketWebService
    extends Service
{

    private final static URL YELLOWJACKETWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException YELLOWJACKETWEBSERVICE_EXCEPTION;
    private final static QName YELLOWJACKETWEBSERVICE_QNAME = new QName("http://soap.j2ee.douai.mines.org/", "YellowJacketWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Mes%20Documents/Travail/ISIC/3A/TP_J2EE/TP_SOAP_SERVLET/src/YellowJacket.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YELLOWJACKETWEBSERVICE_WSDL_LOCATION = url;
        YELLOWJACKETWEBSERVICE_EXCEPTION = e;
    }

    public YellowJacketWebService() {
        super(__getWsdlLocation(), YELLOWJACKETWEBSERVICE_QNAME);
    }

    public YellowJacketWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), YELLOWJACKETWEBSERVICE_QNAME, features);
    }

    public YellowJacketWebService(URL wsdlLocation) {
        super(wsdlLocation, YELLOWJACKETWEBSERVICE_QNAME);
    }

    public YellowJacketWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YELLOWJACKETWEBSERVICE_QNAME, features);
    }

    public YellowJacketWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YellowJacketWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns YellowJacket
     */
    @WebEndpoint(name = "YellowJacketImplPort")
    public YellowJacket getYellowJacketImplPort() {
        return super.getPort(new QName("http://soap.j2ee.douai.mines.org/", "YellowJacketImplPort"), YellowJacket.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YellowJacket
     */
    @WebEndpoint(name = "YellowJacketImplPort")
    public YellowJacket getYellowJacketImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.j2ee.douai.mines.org/", "YellowJacketImplPort"), YellowJacket.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YELLOWJACKETWEBSERVICE_EXCEPTION!= null) {
            throw YELLOWJACKETWEBSERVICE_EXCEPTION;
        }
        return YELLOWJACKETWEBSERVICE_WSDL_LOCATION;
    }

}
