/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TP_SOAP;

import org.junit.Test;
import org.mines.douai.j2ee.soap.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
