/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mines.douai.j2ee.soap;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
